package com.devcourse.be04daangnmarket.post.domain;

public enum Category {

	DIGITAL_DEVICES,
	HOME_APPLIANCES,
	MENS_CLOTHING,
	WOMENS_CLOTHING,
	HOME_KITCHEN,
	HOUSEHOLD_KITCHEN,
	HOBBIES_GAMES_GENERAL,
	FURNITURE_INTERIOR,
	HOME_KITCHEN_CATEGORY
	;

}
